### ISSUE TITLE
Works With PENNYWISE BUT CANT TYPE

### ISSUE THREAD

**Issue by ericlansher** [trympet/lockdown-browser-bypass-macos#13]
Apparently its working with Pennywise application but i am not able to type 
![IMG_6378](https://user-images.githubusercontent.com/73720378/97773003-8d655b00-1b22-11eb-962f-369703640246.JPG)

  IN THE FLOATING browser(pennywise)can someone figure this out ? 
so pennywise app stays on the lockdown browser but the only problem is i wasn't able to search or navigate through the floating browser

**Comment by trympet** [comment]
Duplicate of #12
