### ISSUE TITLE
Bypass for windows

### ISSUE THREAD

**Issue by iTBX** [trympet/lockdown-browser-bypass-macos#14]
Can I know the steps please for windows because unfortunately I don't have that much experience in programming and I am trying to do it with the functions that you mentioned.
Thank you

**Comment by trympet** [comment]
I am sadly no longer able to work on this project. You could perhaps register a hook with the window manager and listen for manipulation of the window order, ensuring that your application of choice always stays on top. Chromium is open source, so it would be a nice starting point.

Have a look at these resources:
https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-windowposchanging
https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-windowposchanged
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms633573(v=vs.85)
