### ISSUE TITLE
it says that there is no module called cocoa

### ISSUE THREAD

**Issue by xyr3x0** [trympet/lockdown-browser-bypass-macos#2]
when I start the script I receive this error
Traceback (most recent call last):
  File "lockdown-bypass.py", line 4, in <module>
    from Cocoa import *
ImportError: No module named Cocoa

is there a way to manually install the module?

**Comment by trympet** [comment]
Hi. I updated the readme with more detailed installation instructions. You can install the missing dependencies (Cocoa) with 
`$ pip3 install -r requirements.txt`
