### ISSUE TITLE
Error when trying to clone repo, and install dependencies

### ISSUE THREAD

**Issue by Strykeros** [trympet/lockdown-browser-bypass-macos#3]
Hello. I get this error when I try to clone the repo and install dependencies:

''ERROR: Could not find a version that satisfies the requirement TBB==0.1 (from -r requirements.txt (line 4)) (from versions: 2018.0.4.1, 2019.0)
ERROR: No matching distribution found for TBB==0.1 (from -r requirements.txt (line 4))''

How can I fix it? Thank you.

**Comment by trympet** [comment]
what is output of `pip3 -V`?

**Comment by Strykeros** [comment]
"pip 20.1.1 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)"

**Comment by trympet** [comment]
try
```
sed -i '/TBB==0.1/d' requirements.txt
```
then
```
pip3 install -r requirements.txt &&
chmod +x lockdown-bypass.py
```

You might not need TBB.

**Comment by Strykeros** [comment]
Now I got this: "sed: -i may not be used with stdin", when I ran the 1st command.

**Comment by trympet** [comment]
ow snap. turns out GNU version of sed is different from BSD. Try
```
sed -i '' '/TBB==0.1/d' requirements.txt
```

**Comment by Strykeros** [comment]
Worked perfectly! Thanks!
