### ISSUE TITLE
Last step in "usage" unclear.

### ISSUE THREAD

**Issue by Strykeros** [trympet/lockdown-browser-bypass-macos#4]
I know I will sound stupid, but how do I do the ''Click a valid lockdown browser URI to start the lockdown browser session within 10 secs.'' step? What is a URI?

**Comment by trympet** [comment]
Hi. No stupid questions 😊

This is the link that you click to start the lockdown browser session. Basically, start the bypass, then start the lockdown browser session.

**Comment by trympet** [comment]
This is what a lockdown browser link looks like `ldb:dh%7BKS6poDqwsi1SHVGEJ+KMYaelPZ56lqcNzohRRiV1bzFj3Hjq8lehqEug88UjowG1mK1Q8h2Rg6j8kFZQX0FdyA==%7D`
