### ISSUE TITLE
Recommend adding the cocoa troubleshooting issues to documentation 

### ISSUE THREAD

**Issue by Neumoon** [trympet/lockdown-browser-bypass-macos#6]
Hi there, I would recommend adding the sed -I “TBB” line for troubleshooting in the dead me as I spent hours figuring out how to make this work on my own  before I found it in your closed issues. I have a feeling this is a common problem with Catalina. Otherwise it works perfectly thank you! Added revision for your review to pull request

Secondly, I am unsure after reading the respondus site, for the physical lockdown browser application, does it record or screen grab our screen and can it see the Helium app open when that is sent to the server? 

Thanks

**Comment by trympet** [comment]
Hi.

Thanks for the PR! 

I haven't used this in quite some time, but I doubt teachers/respondus are willing to spend hours sifting though images/videos. Would be like trying to find the needle in the haystack 😊

Back to the TBB thing; I don't think it's required, as it runs fine for me on Catalina without it. I think the easiest fix would just be to remove TBB from the requirements.
